language: python
python: 2.7
install: "pip install Lektor"
script: 
- lektor build
- '[ "${TRAVIS_BRANCH}" = "source" ] && lektor deploy ghpages || false'
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds